In [12]:
import numpy as np

a = np.arange(11, 30, 2)
print(a)
print("Dimensions:", a.ndim)
print("Total elements:", a.size)

[11 13 15 17 19 21 23 25 27 29]
Dimensions: 1
Total elements: 10


In [13]:
a = np.linspace(5, 35, 7)
print(a)

[ 5. 10. 15. 20. 25. 30. 35.]


In [14]:
a = np.full((4, 3), 9)
a[2, 1] = 0
print(a)

[[9 9 9]
 [9 9 9]
 [9 0 9]
 [9 9 9]]


In [15]:
a = np.array([6, 12, 18, 24])
print(a % 5)

[1 2 3 4]


In [16]:
a = np.array([14, 28, 42, 56, 70, 84])
print(a[1:6:2])

[28 56 84]


In [17]:
a = np.array([-16, 25, -36, 49])
b = np.abs(a)
print(b)
print(np.sqrt(b))

[16 25 36 49]
[4. 5. 6. 7.]


In [18]:
a = np.arange(7, 13).reshape(3, 2)
print(a)
print("Original shape:", a.shape)
print(a.T)
print("Transposed shape:", a.T.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
Original shape: (3, 2)
[[ 7  9 11]
 [ 8 10 12]]
Transposed shape: (2, 3)


In [19]:
temperatures = np.array([18, 22, 27, 31, 24, 19])

print("Range:", np.max(temperatures) - np.min(temperatures))
print("Median:", np.median(temperatures))

Range: 13
Median: 23.0


In [20]:
values = np.array([4, 9, 4, 2, 9, 7, 2, 4])

a = np.unique(values)
print(a)
print("Count:", len(a))

[2 4 7 9]
Count: 4


In [21]:
speed = np.array([35, 62, 48, 81, 55])

result = np.where(speed >= 60, "Fast", "Normal")
print(result)

['Normal' 'Fast' 'Normal' 'Fast' 'Normal']


In [22]:
import pandas as pd
s = pd.Series([24, 31, 19, 27],
              index=['Monday', 'Tuesday', 'Wednesday', 'Thursday'])
print(s)

Monday       24
Tuesday      31
Wednesday    19
Thursday     27
dtype: int64


In [23]:
s = pd.Series([45000, 18000, 22000],
              index=['Laptop', 'Tablet', 'Phone'])
print(s['Tablet'])

18000


In [24]:
rainfall = pd.Series([12, 0, 18, 5, 23])
print(rainfall[rainfall > 10])

0    12
2    18
4    23
dtype: int64


In [25]:
data = {'Gold': 7200, 'Silver': 95, 'Copper': 850}
s = pd.Series(data)

print(s.index)
print(s.values)

Index(['Gold', 'Silver', 'Copper'], dtype='object')
[7200   95  850]


In [26]:
ratings = pd.Series([3.5, 4.2, 2.8, 4.7])
ratings.name = 'Customer Ratings'
ratings.index.name = 'Review ID'

print(ratings)

Review ID
0    3.5
1    4.2
2    2.8
3    4.7
Name: Customer Ratings, dtype: float64


In [27]:
s = pd.Series([11, 22, 33], index=['X1', 'X2', 'X3'])

print('X2 exists:', 'X2' in s.index)
print('X4 is absent:', 'X4' not in s.index)

X2 exists: True
X4 is absent: True


In [28]:
stock = pd.Series([16, 28, 12],
                  index=['Keyboard', 'Mouse', 'Monitor'])

print(stock.to_dict())

{'Keyboard': 16, 'Mouse': 28, 'Monitor': 12}


In [29]:
data = {'Hindi': 78, 'English': 84, 'Computer': 91}
s = pd.Series(data, index=['Computer', 'Hindi', 'Art', 'English'])

print(s)
print("Missing entry:", s.isnull()['Art'])

Computer    91.0
Hindi       78.0
Art          NaN
English     84.0
dtype: float64
Missing entry: True


In [30]:
expenses = pd.Series([1200, None, 850, None, 600])

print(expenses.isnull())
print(expenses.notnull())

0    False
1     True
2    False
3     True
4    False
dtype: bool
0     True
1    False
2     True
3    False
4     True
dtype: bool


In [31]:
a = pd.Series([8, 15, 22], index=['P', 'Q', 'R'])
b = pd.Series([4, 6, 10], index=['R', 'P', 'Q'])

print(a + b)

P    14
Q    25
R    26
dtype: int64
